weights: ''
cfg: ./models/custom_yolov5s.yaml
data: data.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 100
batch_size: 100
imgsz: 240
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 1
project: runs/train
entity: null
name: shot
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
freeze: 0
save_dir: runs/train/shot
